export PATH="/root/.local/bin:$PATH"

# init conda env
source /opt/conda/etc/profile.d/conda.sh 2>/dev/null && conda activate base 2>/dev/null || true

# zsh plugins
source /etc/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /etc/zsh/plugins/zsh-z/zsh-z.plugin.zsh
source /etc/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh

# History substring search keybindings
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Completion
autoload -Uz compinit && compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' +'l:|=* r:|=*'

[[ -f ~/.config/zsh/aliases ]] && source ~/.config/zsh/aliases

setopt AUTO_CD
setopt COMPLETE_IN_WORD
setopt SHARE_HISTORY
setopt APPEND_HISTORY
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

# VCS info for prompt
autoload -Uz vcs_info
precmd() {
  precmd() {
    vcs_info
    echo
  }
}

setopt prompt_subst
zstyle ':vcs_info:git:*' formats ' %b'

export RPROMPT='%F{183}%D{%L:%M}%f'
export PROMPT='%F{183}%1d ${vcs_info_msg_0_}
►%f '
